# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Setup Browser
      uses: abhi1693/setup-browser@v0.3.4
      with:
        browser: chrome
        version: latest
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run the scrappers
      run: python MovieScraper.py
    - name: Commit files
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Updated scraped files'
        author_name: Ahmed Badawe
        author_email: modamoon48@gmail.com

